import path from 'node:path'
import { agentRunner } from '../agent/runner.js'
import { stateManager } from '../state/manager.js'
import { getConfig } from '../config/index.js'
import { createLogger } from '../utils/logger.js'

const log = createLogger('phase4-done')

export async function runPhase4(projectId: number): Promise<void> {
  const config = getConfig()
  const repo = config.repositories.find((r) => r.gitlab_project_id === projectId)
  if (!repo) {
    log.warn({ projectId }, 'No repo config found')
    return
  }

  const state = await stateManager.getProjectState(projectId)
  if (!state) {
    log.warn({ projectId }, 'No state found')
    return
  }

  await stateManager.transitionPhase(projectId, 'MERGING')

  const workspacePath = process.env['WORKSPACE_PATH'] ?? '/workspace'
  const repoAbsPath = path.resolve(workspacePath, repo.local_path)
  const mrIid = state.mrIid
  const iids = state.issueIids

  const prompt = `The MR has been approved for project ${repo.name}. Execute the Done phase.
GitLab project ID: ${repo.gitlab_project_id}
MR IID: ${mrIid}
Issues to close: ${iids.join(', ')}
Working directory: ${repoAbsPath}

STEP 1 — MERGE MR:
  glab mr merge ${mrIid} --squash=false --delete-source-branch

  If merge fails due to conflicts:
    git fetch origin
    git checkout {sourceBranch}
    git merge origin/main
    (Resolve conflicts in conflicted files)
    git add -A
    git commit -m "chore: resolve merge conflicts"
    git push origin {sourceBranch}
    Then retry: glab mr merge ${mrIid}

STEP 2 — VERIFY MERGE:
  glab mr view ${mrIid} --output json
  Confirm state === 'merged'

STEP 3 — CLOSE ALL ISSUES:
  For each issue IID in [${iids.join(', ')}]:
    glab issue close {iid}
    glab issue note {iid} --message "✅ Closed — implemented and merged in MR !${mrIid}"

STEP 4 — CLEANUP LOCAL BRANCHES:
  git fetch --prune
  Delete any remaining local feature branches

STEP 5 — GENERATE FINAL REPORT and POST:
  glab mr note ${mrIid} --message "## 🎉 Project Implementation Complete!

**Completed:** $(date -u +%Y-%m-%dT%H:%M:%SZ)
**MR:** !${mrIid}

### Issues Completed (${iids.length} total)
${iids.map((iid) => `- ✅ #${iid}`).join('\n')}

### Summary
All planned features have been implemented, tested, and merged.

---
*Generated by AI Agent*"

STEP 6 — Output on final line:
  PHASE_COMPLETE: done

Always use absolute paths starting with ${repoAbsPath}.`

  log.info({ projectId, mrIid }, 'Starting Phase 4 — merge and cleanup')

  const result = await agentRunner.run({
    prompt,
    cwd: repoAbsPath,
    onProgress: (msg) => log.debug({ msg: msg.slice(0, 120) }, 'Agent progress'),
  })

  if (result.output.includes('PHASE_COMPLETE: done')) {
    await stateManager.transitionPhase(projectId, 'COMPLETE')
    log.info({ projectId }, 'Project complete!')
  } else {
    log.warn({ projectId }, 'PHASE_COMPLETE not found in agent output')
  }
}
